### ISSUE TITLE
imdone breaks markdown todo items with embedded HTML comments

### ISSUE THREAD

**Issue by bluebirch** [imdone/imdone#119]
**Describe the bug**

Imdone gets it wrong if I create a markdown todo with a HTML comment:
```markdown
- [ ] [Text <!-- @tag -->](#TODO:0)
```
When I move this to DONE, it becomes:
```markdown
- [x] [Text <!-- @tag](#DONE:-56)
  completed:2021-12-02T12:16:27.913Z
  -->
```

**Expected behavior**

I would expect imdone to keep the HTML comment intact within the markdown link.

I would suggest that *if* there is a HTML comment tag in the markdown link, that everything is moved there by default:
```markdown
- [x] [Text <!-- @tag completed:2021-12-02T12:16:27.913Z -->](#DONE:-56)
```
HTML comments betwen items in markdown lists are interpreted as whitespace by many markdown engines, resulting in a list with larger line spacing. That is why I would prefer imdone to use the comment in the markdown link if it exists.

**DoD**
- [ ] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release
