### ISSUE TITLE
Hashtag syntax not working 1.6.10

### ISSUE THREAD

**Issue by Owen-Davies** [imdone/imdone#40]
The creation of new tasks with hashtag syntax doesn't work on Windows or Linux.

When I change the board settings (and default settings), the cards are created with the following syntax:
```
# [test](#TODO:0)
<!--
created:2020-12-15T15:43:44.471Z
-->
``` 

**To Reproduce**
1. Change board settings
2. Change _Journal type_ to single file
3. Change _single journal file_ to *todo.txt*
4. Change _New card syntax_ to HASHTAG
5. Click Save Settings
6. Close board settings
7.  Click Add a Card
8. Type Test
9. Save
10. View todo.txt file
11. Still in markdown format

**Expected behavior**
Expected to move to hashtag syntax

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10 & Windows !0
 - Browser Chrome & Firefox

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
Thanks for reporting this @Owen-Davies.  Does it work if you restart imdone?

**Comment by Owen-Davies** [comment]
Doesn't seem to I keep restarting it

**Comment by Owen-Davies** [comment]
If I manually add 

```
#TODO:0 This is HASHTAG syntax created:2020-12-15
```

It interprets it ok though.

**Comment by Owen-Davies** [comment]
Seems to have updated the config file ok

```
keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
    hidden: true
    id: 0
    name: What's Due?
  - hidden: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    ignore: true
    name: DONE
  - filter: 'completedDate > "${7 days ago}" -completed'
    hidden: false
    id: 1
    name: Recently Completed
settings:
  journalType: Single File
  journalPath: static
  taskPrefix: '#'
  maxLines: 6
  addNewCardsToTop: true
  newCardSyntax: HASHTAG
  replaceSpacesWith: '-'
  cards:
    colors: []
    links:
      - href: >-
          https://twitter.com/intent/tweet?text=${encodedText}%0ATweeted%20with%20@imdoneio
        icon: fa-twitter
        pack: fab
        title: Tweet this card
    computed:
      date: (new Date()).toDateString()
      time: (new Date()).toLocaleTimeString()
      timestamp: (new Date()).toISOString()
    template: |

      <!--
      created:${(new Date()).toISOString()}
      -->
  doneList: DONE
  filteredLists:
    - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
      name: What's Due?
    - filter: 'completedDate > "${7 days ago}" -completed'
      name: Recently Completed
  journalTemplate: null
  appendNewCardsTo: todo.txt

```

**Comment by piascikj** [comment]
I've found the issue and will have a patch ready later today.  It will be 1.6.11.

**Comment by piascikj** [comment]
This is now fixed in 1.6.11.  Thanks for reporting!

**Comment by Owen-Davies** [comment]
wow, speedy guys! Nice work

I'm getting the following for a new task:

```
# #TODO:0 new card from 1.6.11
```

Is the double # correct behavior?

Also, would it be possible to have the #TODO:0 at the end of the line? It would look better in other todo.txt apps
