### ISSUE TITLE
meta values truncate on a variety of characters

### ISSUE THREAD

**Issue by tf13** [imdone/imdone#63]
**Describe the bug**
The following card meta entries will, when used in a card, truncate as indicated if added to a card as `foo: ${foo}`:

`foo:path/to/bar`
> foo: path

`foo:baz%bar`
> foo: baz

`foo:spacy%20bar`
> foo: spacy

**Expected behavior**
It would be nice if encoded characters, at least, would render properly. In particular, this could allow the incorporation of paths constructed using custom metadata. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser imdone Mac app, latest version

**Additional context**

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
Fixed in 1.13.1
