### ISSUE TITLE
Epic Tracking

### ISSUE THREAD

**Issue by zgagnon** [imdone/imdone#78]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up "epic" items - items that track the progress of several other cards.  I would like to have one place to track the progress of a big initiative through small cards, with the least manual effort possible

Basically,
**Describe the solution you'd like**
When I tag a card with a certain tag, I would like to be able to see that card appear in some place (another card or list) automatically. I would like that place to have (at minimum) a progress bar to show how many of the tagged items are done, and ideally a burn-up chart to show overall progress as new items are added.

**Describe alternatives you've considered**
Manually tracking through a card:
```
360 Process
<!--
created:2021-03-18T13:55:36.447Z
-->

- [ ] Get small-improvements account
- [ ] Ask for small-improvements volunteers [[Small-Improvements-Call-for-Volunteers]]
- [ ] Get Review nominations [[Gather-small-improvements-review-candidates]]
- [ ] Determine reviewers [[Match-Small-Improvements-reviewers]] 
- [ ] Send out 360s [[Send-Out-Small-Improvements-360s]]
```

**Additional context**

Here is a picture of a burn-up chart:

![Burn up Chart 3](https://user-images.githubusercontent.com/324922/111649182-8477dc00-87da-11eb-8370-ca0ff2061f8f.gif)

Here is an article about how Pivotal Tracker accomplishes this with lists and labels: https://www.pivotaltracker.com/blog/using-epics-for-your-project

**Comment by jtmusky** [comment]
This is a great idea. Should it include any subtasks from those reference cards? 

> When I tag a card with a certain tag, I would like to be able to see that card appear in some place (another card or list) automatically.

Idea 💡: I think this might done via a filtered list under the board settings. Something like `metaKeys = epic` if you use `epic:Start_a_Chicken_farm` in a card.

**Comment by zgagnon** [comment]
I'm personally more interested in tracking completed work than progress through an individual work item. I feel subtask lists adequately fit my needs for that.

**Comment by piascikj** [comment]
The first part of this has been implemented in 1.16.4 with `epic` and `is-epic` meta keys.  The burn-up can be accomplished with a custom board command to export csv data. I'm gonna call this done and you can open another feature request for burn-up if you wish.
